# Generated by Django 4.2.6 on 2023-10-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admins',
            options={'verbose_name': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Users'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='defaults/default_profile.jpg', upload_to='profile_images/'),
        ),
    ]
