# Generated by Django 4.2.6 on 2023-11-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('ip_address', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=8)),
            ],
        ),
    ]
