# Generated by Django 4.2.6 on 2023-12-02 21:27

from django.db import migrations, models
import users.models_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default_profile.jpg', null=True, upload_to=users.models_helpers.get_image_path),
        ),
    ]
