# Generated by Django 4.2.6 on 2023-10-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customusers',),
        ),
        migrations.AddField(
            model_name='customusers',
            name='type',
            field=models.CharField(choices=[('SERVICE_PROVIDER', 'Service_Provider'), ('USER', 'User')], default='USER', max_length=50, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('customusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('isbn_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.serviceproviderproxy',),
        ),
    ]
