# Generated by Django 4.2.6 on 2023-10-26 16:00

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='defaults/default_profile.jpg', upload_to=users.utils.unique_image_name),
        ),
    ]
