# Generated by Django 4.2.6 on 2023-10-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_serviceproviderproxy_customusers_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='customusers_ptr',
        ),
        migrations.DeleteModel(
            name='ServiceProviderProxy',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
