# Generated by Django 4.2.6 on 2023-11-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
