# Generated by Django 4.2.6 on 2023-10-26 05:41

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', users.models.CusotmManager()),
            ],
        ),
    ]
