# Generated by Django 4.2.6 on 2023-11-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
    ]
