# Generated by Django 4.2.6 on 2023-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_serviceprovider_customusers_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customusers',),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='type',
            field=models.CharField(choices=[('SERVICE_PROVIDER', 'Service_Provider'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=50, verbose_name='Type'),
        ),
    ]
