# Generated by Django 4.2.6 on 2023-10-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admins',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admin'},
        ),
        migrations.AlterModelOptions(
            name='superadmins',
            options={'verbose_name': 'SuperAdmin', 'verbose_name_plural': 'SuperAdmin'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
