# Generated by Django 4.2.6 on 2023-11-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('SERVICE_PROVIDER', 'Service_Provider'), ('SUPER_ADMIN', 'Super_Admin'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=16),
        ),
    ]
