# Generated by Django 4.2.6 on 2023-11-11 06:37

from django.db import migrations, models
import users.models_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_users_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='defaults/default_profile.jpg', upload_to=users.models_helpers.get_image_path),
        ),
    ]
