# Generated by Django 4.2.6 on 2023-11-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_emailconfirmation_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChange',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=16, unique=True)),
                ('new_email', models.EmailField(max_length=64, unique=True)),
            ],
        ),
    ]
