# Generated by Django 4.2.6 on 2023-11-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_emailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='ip_address',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
