# Generated by Django 4.2.6 on 2023-11-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_emailconfirmation_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='token',
        ),
    ]
