# Generated by Django 4.2.6 on 2023-11-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_emailconfirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='email',
            field=models.EmailField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
