# Generated by Django 4.2.6 on 2023-11-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='code',
            field=models.CharField(default='', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
