# Generated by Django 4.2.6 on 2023-11-12 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_passwordreset_ip_address_passwordreset_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='email',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='ip_address',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
