# Generated by Django 4.2.6 on 2023-12-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='ar_content',
        ),
        migrations.AddField(
            model_name='notification',
            name='en_content',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
    ]
