# Generated by Django 4.2.6 on 2023-12-07 06:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_productrates_productrates_user_service_constraint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRates',
            new_name='ServiceRates',
        ),
    ]
