# Generated by Django 4.2.6 on 2023-11-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ar_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
