# Generated by Django 4.2.6 on 2023-10-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('DENTAL', 'Dental'), ('OPTICS', 'Optics'), ('NUTRITIONIST', 'Nutritionist'), ('HOME_CARE', 'Home Care'), ('PLASTIC_SURGERY', 'Plastic Surgery'), ('RADIOLOGIST', 'Radiologist'), ('AESTHETICS', 'Aesthetics'), ('PHARMACY', 'Pharmacy'), ('HOSPITAL', 'Hospital'), ('LAB', 'Lab'), ('CLINIC', 'Clinic')], max_length=20, unique=True),
        ),
    ]
