# Generated by Django 4.2.6 on 2023-10-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_translatedcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedcategory',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='name', to='category.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translatedcategory',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
