# Generated by Django 4.2.6 on 2023-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_myategory_mycategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycategorytranslation',
            old_name='name',
            new_name='ar_name',
        ),
        migrations.AddField(
            model_name='mycategory',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
