# Generated by Django 4.2.6 on 2023-11-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_ar_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='en_name',
        ),
    ]
