# Generated by Django 4.2.6 on 2023-10-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_translatedcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedcategory',
            name='language_code',
            field=models.CharField(choices=[('EN', 'En'), ('AR', 'Ar')], default='', max_length=4),
            preserve_default=False,
        ),
    ]
