# Generated by Django 4.2.6 on 2023-10-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_translatedcategory_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TranslatedCategory',
        ),
    ]
