# Generated by Django 4.2.6 on 2023-11-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_name_delete_translatedcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.JSONField(max_length=32),
        ),
    ]
