# Generated by Django 4.2.6 on 2023-12-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointmentsdraft_user_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointmentsdraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointmentsdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RejectedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_appointments', to='appointments.appointmentsdraft')),
            ],
        ),
    ]
