# Generated by Django 4.2.6 on 2023-12-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointments_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='appointments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rejectedappointments',
            name='draft_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_appointments', to='appointments.appointments'),
        ),
        migrations.DeleteModel(
            name='AppointmentsDraft',
        ),
    ]
