# Generated by Django 4.2.6 on 2023-12-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointments_status_appointments_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedappointments',
            name='draft_appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_appointments', to='appointments.appointments'),
        ),
    ]
