# Generated by Django 4.2.6 on 2023-12-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_rejectedappointments_draft_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejectedappointments',
            old_name='draft_appointment',
            new_name='appointment',
        ),
    ]
