<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-11-04 07:30
=======
# Generated by Django 4.2.6 on 2023-11-01 05:08
>>>>>>> 2cae0b29be463970214a119aafc2aa1dc4fdf307

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 2cae0b29be463970214a119aafc2aa1dc4fdf307
        ('category', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=128, unique=True)),
                ('contact_number', models.CharField(max_length=16, unique=True)),
                ('bank_name', models.CharField(max_length=128)),
                ('iban', models.CharField(max_length=40, unique=True)),
                ('swift_code', models.CharField(max_length=16, unique=True)),
                ('provider_file', models.FileField(upload_to='service_providers/documents/')),
                ('account_status', models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_services', to='users.admins')),
<<<<<<< HEAD
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.mycategory')),
=======
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
>>>>>>> 2cae0b29be463970214a119aafc2aa1dc4fdf307
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ServiceProvider',
                'verbose_name_plural': 'ServiceProviders',
                'ordering': ['date_joined'],
            },
            bases=('users.users',),
        ),
        migrations.CreateModel(
            name='ServiceProviderLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('crew', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'ServiceProviderLocations',
                'verbose_name_plural': 'ServiceProviderLocations',
            },
        ),
    ]
