# Generated by Django 4.2.6 on 2023-11-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofilerequests',
            old_name='approved_by',
            new_name='checked_by',
        ),
        migrations.RenameField(
            model_name='updateprofilerequests',
            old_name='user_requested',
            new_name='provider_requested',
        ),
        migrations.RemoveField(
            model_name='serviceproviderlocations',
            name='service_provider_id',
        ),
        migrations.RemoveField(
            model_name='updateprofilerequests',
            name='request_type',
        ),
        migrations.AddField(
            model_name='serviceproviderlocations',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='service_providers.serviceprovider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_providers', to='category.category'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='serviceproviderlocations',
            name='crew',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='updateprofilerequests',
            name='request_status',
            field=models.CharField(default='Pending', max_length=25, null=True),
        ),
    ]
