# Generated by Django 4.2.6 on 2023-10-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['date_joined'], 'verbose_name': 'ServiceProvider', 'verbose_name_plural': 'ServiceProviders'},
        ),
    ]
