# Generated by Django 4.2.6 on 2023-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderlocations',
            name='address',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
