# Generated by Django 4.2.6 on 2023-12-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofilerequests',
            old_name='updated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='updateprofilerequests',
            name='request_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=15),
        ),
    ]
