# Generated by Django 4.2.6 on 2023-11-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofilerequests',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='updateprofilerequests',
            name='request_status',
            field=models.CharField(default='Pending', max_length=25, null=True),
        ),
    ]
