# Generated by Django 4.2.6 on 2023-11-04 07:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_remove_serviceproviderlocations_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderlocations',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
