# Generated by Django 4.2.6 on 2023-12-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_rename_updated_at_updateprofilerequests_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprofilerequests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
