# Generated by Django 4.2.6 on 2023-11-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_alter_serviceprovider_provider_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproviderlocations',
            old_name='service_provider_id',
            new_name='service_provider',
        ),
    ]
