# Generated by Django 4.2.6 on 2023-11-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_rename_approved_by_updateprofilerequests_checked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='bank_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='business_name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='iban',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='swift_code',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
