# Generated by Django 4.2.6 on 2023-11-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailconfirmation_remove_users_date_joined_and_more'),
        ('category', '0001_initial'),
        ('service_providers', '0002_updaterequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'verbose_name': 'ServiceProvider', 'verbose_name_plural': 'ServiceProviders'},
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_services', to='users.admins'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_providerd', to='category.category'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(null=True, upload_to='service_providers/documents/'),
        ),
        migrations.DeleteModel(
            name='UpdateRequest',
        ),
    ]
