# Generated by Django 4.2.6 on 2023-10-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_serviceprovider_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('service_provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceprovider')),
            ],
        ),
    ]

    