# Generated by Django 4.2.6 on 2023-11-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_alter_serviceprovider_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='bank_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='business_name',
            field=models.CharField(default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='iban',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='swift_code',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
