# Generated by Django 4.2.6 on 2023-11-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_rename_service_provider_id_serviceproviderlocations_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderlocations',
            name='crew',
            field=models.CharField(max_length=512),
        ),
    ]
