# Generated by Django 4.2.6 on 2023-11-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_serviceproviderlocations_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderlocations',
            name='service_provider_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceprovider'),
            preserve_default=False,
        ),
    ]
