# Generated by Django 4.2.6 on 2023-10-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_alter_serviceprovider_service_provider_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='service_provider_id',
            new_name='user',
        ),
    ]
