# Generated by Django 4.2.6 on 2023-11-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('service_providers', '0003_alter_serviceprovider_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateProfileRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_data', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_approved_profile_requests', to='users.admins')),
                ('user_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceprovider')),
            ],
        ),
    ]
