# Generated by Django 4.2.6 on 2023-11-14 05:26

from django.db import migrations, models
import service_providers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_remove_serviceprovider_provider_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(null=True, upload_to=service_providers.helpers.get_file_path),
        ),
    ]
