# Generated by Django 4.2.6 on 2023-10-27 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_serviceproviderlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderlocation',
            name='closing',
            field=models.TimeField(null=False)
        ),
        migrations.AddField(
            model_name='serviceproviderlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=False),
        ),
        migrations.AddField(
            model_name='serviceproviderlocation',
            name='crew',
            field=models.CharField(max_length=32, null=False),
        ),
        migrations.AddField(
            model_name='serviceproviderlocation',
            name='opening',
            field=models.TimeField(null=False),
        ),
    ]
