# Generated by Django 4.2.6 on 2023-12-05 14:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_updateprofilerequests_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderlocations',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
