# Generated by Django 4.2.6 on 2023-11-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0004_alter_serviceproviderlocations_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderlocations',
            name='crew',
            field=models.TextField(),
        ),
    ]
