# Generated by Django 4.2.6 on 2023-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0004_updateprofilerequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprofilerequests',
            name='approved_or_declined',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='updateprofilerequests',
            name='request_type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
