# Generated by Django 4.2.6 on 2023-11-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_name'),
        ('service_providers', '0004_alter_serviceproviderlocations_service_provider_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['user__date_joined'], 'verbose_name': 'ServiceProvider', 'verbose_name_plural': 'ServiceProviders'},
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_providerd', to='category.category'),
        ),
    ]
