# Generated by Django 4.2.6 on 2023-10-26 05:41

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0004_rename_service_provider_id_serviceprovider_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='serviceprovider',
            managers=[
                ('objects', users.models.CusotmManager()),
            ],
        ),
    ]
