# Generated by Django 4.2.6 on 2023-10-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_admins_options_alter_superadmins_options_and_more'),
        ('service_providers', '0004_rename_service_provider_id_serviceprovider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='account_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_services', to='users.admins'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='contact_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='iban',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='swift_code',
            field=models.CharField(max_length=16),
        ),
    ]
