# Generated by Django 4.2.6 on 2023-11-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0004_serviceprovider_provider_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
