# Generated by Django 4.2.6 on 2023-10-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0004_serviceproviderlocation_closing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceProviderLocation',
            new_name='ServiceProviderLocations',
        ),
        migrations.AlterModelOptions(
            name='serviceproviderlocations',
            options={'verbose_name': 'ServiceProviderLocations', 'verbose_name_plural': 'ServiceProviderLocations'},
        ),
    ]
