# Generated by Django 4.2.6 on 2023-11-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0005_alter_serviceprovider_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='contact_number',
        ),
    ]
