# Generated by Django 4.2.6 on 2023-10-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0005_alter_serviceprovider_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='business_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='contact_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='iban',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='swift_code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
