# Generated by Django 4.2.6 on 2023-11-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('service_providers', '0005_alter_serviceproviderlocations_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_providers', to='category.category'),
        ),
        migrations.AlterField(
            model_name='serviceproviderlocations',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='service_providers.serviceprovider'),
        ),
    ]
