# Generated by Django 4.2.6 on 2023-11-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('service_providers', '0005_updateprofilerequests_approved_or_declined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofilerequests',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_approved_profile_requests', to='users.admins'),
        ),
    ]
