# Generated by Django 4.2.6 on 2023-11-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0006_alter_serviceprovider_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofilerequests',
            name='request_type',
        ),
    ]
