# Generated by Django 4.2.6 on 2023-11-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0006_alter_updateprofilerequests_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofilerequests',
            old_name='approved_or_declined',
            new_name='request_status',
        ),
    ]
