# Generated by Django 4.2.6 on 2023-11-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0007_remove_updateprofilerequests_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofilerequests',
            name='request_status',
            field=models.CharField(default='Pending', max_length=25, null=True),
        ),
    ]
