# Generated by Django 4.2.6 on 2023-11-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_image'),
        ('service_providers', '0007_remove_serviceprovider_provider_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'verbose_name': 'ServiceProvider', 'verbose_name_plural': 'ServiceProviders'},
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_services', to='users.admins'),
        ),
    ]
