# Generated by Django 4.2.6 on 2023-11-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0008_alter_updateprofilerequests_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofilerequests',
            old_name='approved_by',
            new_name='checked_by',
        ),
    ]
