# Generated by Django 4.2.6 on 2023-11-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0008_alter_serviceprovider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(null=True, upload_to='service_providers/documents/'),
        ),
    ]
