# Generated by Django 4.2.6 on 2023-11-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0009_rename_approved_by_updateprofilerequests_checked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofilerequests',
            old_name='user_requested',
            new_name='provider_requested',
        ),
    ]
