# Generated by Django 4.2.6 on 2023-11-10 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_remove_emailconfirmation_user_and_more'),
        ('category', '0003_alter_category_name'),
        ('service_providers', '0011_remove_serviceproviderlocations_service_provider_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=128, unique=True)),
                ('bank_name', models.CharField(max_length=128)),
                ('iban', models.CharField(max_length=40, unique=True)),
                ('swift_code', models.CharField(max_length=16, unique=True)),
                ('provider_file', models.FileField(null=True, upload_to='service_providers/documents/')),
                ('account_status', models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_services', to='users.admins')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_providerd', to='category.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ServiceProvider',
                'verbose_name_plural': 'ServiceProviders',
            },
            bases=('users.users',),
        ),
    ]
