# Generated by Django 4.2.6 on 2023-11-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0012_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderlocations',
            name='service_provider_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceprovider'),
            preserve_default=False,
        ),
    ]
