# Generated by Django 4.2.6 on 2023-11-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0013_serviceproviderlocations_service_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(default='defaults/default_profile.jpg', upload_to='service_providers/documents/'),
        ),
    ]
