# Generated by Django 4.2.6 on 2023-11-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0014_alter_serviceprovider_provider_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(null=True, upload_to='service_providers/documents/'),
        ),
    ]
