# Generated by Django 4.2.6 on 2023-11-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0016_alter_serviceprovider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(default='request.jpg', upload_to='service_providers/documents/'),
            preserve_default=False,
        ),
    ]
