# Generated by Django 4.2.6 on 2023-11-11 06:37

from django.db import migrations, models
import service_providers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0017_alter_serviceprovider_provider_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_file',
            field=models.FileField(upload_to=service_providers.helpers.get_file_path),
        ),
    ]
