# Generated by Django 4.2.6 on 2023-11-05 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='service_provider_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service_providers.serviceproviderlocations'),
        ),
    ]
