# Generated by Django 4.2.6 on 2023-11-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
