# Generated by Django 4.2.6 on 2023-12-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_cartitems_cart_cartitems_patient_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectedorders',
            name='id',
        ),
        migrations.AlterField(
            model_name='rejectedorders',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reject_table', serialize=False, to='orders.orderitem'),
        ),
    ]
