# Generated by Django 4.2.6 on 2023-12-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_rejectedorders_id_alter_rejectedorders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='updated_at',
            new_name='last_update',
        ),
    ]
