# Generated by Django 4.2.6 on 2023-12-07 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='last_update',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
