# Generated by Django 4.2.6 on 2023-11-30 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_cart_price_remove_cart_product_and_more'),
        ('deliveries', '0002_remove_delivery_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='paid',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.orderitem'),
        ),
    ]
