# Generated by Django 4.2.6 on 2023-12-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_rejectedorders_id_alter_rejectedorders_order'),
        ('deliveries', '0003_remove_delivery_paid_alter_delivery_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='id',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery', serialize=False, to='orders.orderitem'),
        ),
    ]
