# Generated by Django 4.2.6 on 2023-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discount_ammount',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
    ]
