# Generated by Django 4.2.6 on 2023-11-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_providers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_provider_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceproviderlocations'),
        ),
    ]
