# Generated by Django 4.2.6 on 2023-11-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
