# Generated by Django 4.2.6 on 2023-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
