# Generated by Django 4.2.6 on 2023-12-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productrates_productrates_user_product_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrates',
            name='rate',
            field=models.SmallIntegerField(default=0),
        ),
    ]
