# Generated by Django 4.2.6 on 2023-12-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
