# Generated by Django 4.2.6 on 2023-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productrates_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(max_length=255),
        ),
    ]
